# Generated by Django 3.2.6 on 2021-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210817_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='view_count',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=10),
        ),
    ]
