# Generated by Django 3.2.6 on 2021-08-17 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 14, 48, 36, 331085, tzinfo=utc)),
        ),
    ]
